apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice
  labels:
    app.kubernetes.io/name: checkoutservice
    app.kubernetes.io/instance: checkoutservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
