apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
  labels:
    pp.kubernetes.io/name: productcatalogservice
    app.kubernetes.io/instance: productcatalogservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
