apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  labels:
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/instance: currencyservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
