apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  labels:
    app.kubernetes.io/name: adservice
    app.kubernetes.io/instance: adservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
