apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
  labels:
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
