apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    pp.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
