apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice
  labels:
    pp.kubernetes.io/name: emailservice
    app.kubernetes.io/instance: emailservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
