apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
  labels:
    pp.kubernetes.io/name: loadgenerator
    app.kubernetes.io/instance: loadgenerator
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
