apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  labels:
    pp.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
