apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
  labels:
    pp.kubernetes.io/name: paymentservice
    app.kubernetes.io/instance: paymentservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
