apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentservice-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: paymentservice
      app.kubernetes.io/instance: paymentservice
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: online-boutique