apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommadationservice
  labels:
    pp.kubernetes.io/name: recommadationservice
    app.kubernetes.io/instance: recommadationservice
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: online-boutique
