{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "ob.labels" (dict "name" $name "component" "service" "root" $) | nindent 4 }}
data:
  {{- range $k, $v := $svc.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
